name: primeira-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu primeiro job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        run: echo "Hello World !!!"
      - name: "Segunda ação"
        run: |
          echo "Você criou o seu primeiro workflow !!!"
          echo "Parabéns"
      - name: "Script Phyton"
        run: |
          variavel = "Hellow World Python!!!"
          print(variavel)
        shell: python
  segundo-job:
    name: "Instalação do Ambiente NodeJS"
    runs-on: ubuntu-latest
    needs: primeiro-job
    steps:
      - name: "Verificação da versão do NodeJS atual"
        run: node --version || echo "NodeJS não está instalado"
      - name: "Definição da versão do NodeJS"
        uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: "Verificação da versão do NodeJS após atualização"
        run: node --version || echo "NodeJS não está instalado"
